name: Test Docker on GitHub Actions

on:
  pull_request:
  push:
    branches: 
      - main
      - docker-compose-build

jobs:
  cardamon:
    runs-on: ubuntu-latest
    env:
      DOCKER_SOCK: unix:///var/run/docker.sock 
    container:
      image: flyaruu/cardamon_cicd:0.2.9
      options: --privileged --shm-size=2g
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docker compose
        run: |
          docker compose build
      - name: Cardamon
        run: |
          export LOG_FILTER=info
          touch .stderr
          touch .stdout
          cardamon run spacetime
      - name: Log
        if: always()
        run: |
          cat .stderr
      - name: Log
        if: always()
        run: |
          cat .stdout
      - uses: actions/upload-artifact@v4
        with:
          name: cardamon-metrics
          path: cardamon.db
